import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from 'next/link'
import NextCors from 'nextjs-cors'

async function handler(req, res) {
   // Run the cors middleware
   // nextjs-cors uses the cors package, so we invite you to check the documentation https://github.com/expressjs/cors
   await NextCors(req, res, {
      // Options
      methods: ['GET', 'HEAD', 'PUT', 'PATCH', 'POST', 'DELETE'],
      origin: '*',
      optionsSuccessStatus: 200, // some legacy browsers (IE11, various SmartTVs) choke on 204
   });

   // Rest of the API logic
   res.json({ message: 'Hello NextJs Cors!' });
}

//--------------------------------------------------------------

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Hobby Helper</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/HELPlogo.png" />
      </Head>

      <main className={styles.main}>
        <h1 className="title">
          Hobby Helper
          <span className={styles.logo}>
            <Image src="/HELPlogo.png" alt="Vercel Logo" width={70} height={75} />
          </span>
        </h1>

      <h3>Track what excites you!</h3>

      <Link href="/about">
      <a>About Us</a>
      </Link>

        <div>
        <Link href="/create-hobby">
        <button type="submit">Click to Add New Hobby</button>
        </Link>
        </div>

        <div>
        <Link href="/create-budget">
        <button type="submit">Create a Budget!</button>
        </Link>
        </div>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/master/examples"
            className={styles.card}
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div>
      </main>
      <footer className={styles.footer}>
        <a>
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/HELPlogo.png" alt="Vercel Logo" width={55} height={60} />
          </span>
          Just.B.Poz Enterprises
        </a>
      </footer>
    </div>
     
  )
}
